//! Compare optimized execution against a naive reference on random programs.

use std::io::Cursor;

use super::int::Interpreter;
#[cfg(feature = "jit")]
use super::jit::JITTarget;
use super::test_buffer::TestBuffer;
use crate::parser::{AstNode, Operand, max_offset};

const TAPE: usize = 64;
/// Programs start by moving to the middle of the tape so they can move left.
const START: usize = 32;
const INPUT: &[u8] = &[7, 0, 255, 1, 3, 128, 2, 254, 9, 0, 1, 5];

/// Multi-byte arithmetic, as generated by compilers targeting brainfuck, and
/// code printing the cells holding the result.
const MULTI_BYTE: &[(&str, &str)] = &[
    // Cells are counter, low byte, high byte, two temporaries.
    // Add the counter with carry: `+` then `high += (low == 0)`
    (
        "[->+>>[-]>[-]+<<<[->>+>[-]<<<]>>[-<<+>>]>[-<<+>>]<<<<]",
        ".>.>.",
    ),
    // Subtract the counter with borrow: `high -= (low == 0)` then `-`
    (
        "[->>>[-]>[-]+<<<[->>+>[-]<<<]>>[-<<+>>]>[-<<->>]<<<-<]",
        ".>.>.",
    ),
    // Same with the counter stepping up
    (
        "[+>+>>[-]>[-]+<<<[->>+>[-]<<<]>>[-<<+>>]>[-<<+>>]<<<<]",
        ".>.>.",
    ),
    // Three byte increment, propagating the carry with nested ifs
    (
        concat!(
            "[->>>>>>[-]<<<<<+>>>[-]>[-]+<<<<[->>>+>[-]<<<<]>>>[-<<<+>>>]",
            ">[-<<<+>>[-]>>[-]+<<<<[->>+>>[-]<<<<]>>[-<<+>>]>>[-<<<+>>>]<]<<<<<]"
        ),
        ".>.>.>.",
    ),
    // Multiply and accumulate: add cell 1 to the two byte number at cells 3
    // and 4 counter times, by copying it to cell 2 (with temporary cell 7)
    // and adding that with carry.
    (
        concat!(
            "[->>[-]>>>>>[-]<<<<<<[->+>>>>>+<<<<<<]>>>>>>[-<<<<<<+>>>>>>]<<<<<",
            "[->+>>[-]>[-]+<<<[->>+>[-]<<<]>>[-<<+>>]>[-<<+>>]<<<<]<<]"
        ),
        ".>.>>.>.",
    ),
];

struct Rng(u64);

impl Rng {
    fn next(&mut self) -> u64 {
        self.0 ^= self.0 << 13;
        self.0 ^= self.0 >> 7;
        self.0 ^= self.0 << 17;
        self.0
    }

    fn below(&mut self, n: usize) -> usize {
        usize::try_from(self.next() % n as u64).unwrap()
    }
}

/// Random program biased towards loop idioms the optimizer recognizes.
fn generate(rng: &mut Rng, depth: usize, out: &mut String) {
    for _ in 0..=rng.below(8) {
        match rng.below(15) {
            0..=2 => out.push_str(["+", "-", "+++", "-----"][rng.below(4)]),
            3..=4 => out.push_str([">", "<", ">>", "<<"][rng.below(4)]),
            5 => out.push(','),
            6 => out.push('.'),
            7 => out.push_str(["[-]", "[>]", "[<<]", "[->+<]", "[->>+++<<]"][rng.below(5)]),
            8 => out.push_str(MULTI_BYTE[rng.below(MULTI_BYTE.len())].0),
            _ if depth < 3 => {
                // A loop with a balanced body, sometimes stepping the counter.
                out.push('[');
                if rng.below(2) == 0 {
                    out.push_str(["-", "+", "---", "+++"][rng.below(4)]);
                }
                let mut body = String::new();
                generate(rng, depth + 1, &mut body);
                let balance: i32 = body
                    .chars()
                    .map(|c| match c {
                        '>' => 1,
                        '<' => -1,
                        _ => 0,
                    })
                    .sum();
                out.push_str(&body);
                if rng.below(4) != 0 {
                    let fix = if balance > 0 { "<" } else { ">" };
                    out.push_str(&fix.repeat(balance.unsigned_abs() as usize));
                }
                out.push(']');
            }
            _ => out.push('+'),
        }
    }
}

/// Naive brainfuck. Returns `None` if the program misbehaves or runs too long.
fn reference(program: &[u8], input: &[u8], steps: usize) -> Option<(Vec<u8>, Vec<u8>)> {
    let mut tape = vec![0u8; TAPE];
    let mut output = Vec::new();
    let mut input = input.iter();
    let (mut pc, mut ptr) = (0, 0);

    for _ in 0..steps {
        let Some(&op) = program.get(pc) else {
            return Some((tape, output));
        };
        match op {
            b'+' => tape[ptr] = tape[ptr].wrapping_add(1),
            b'-' => tape[ptr] = tape[ptr].wrapping_sub(1),
            b'>' => ptr = (ptr + 1 < TAPE).then_some(ptr + 1)?,
            b'<' => ptr = ptr.checked_sub(1)?,
            b'.' => output.push(tape[ptr]),
            b',' => tape[ptr] = input.next().copied().unwrap_or(b'\n'),
            b'[' if tape[ptr] == 0 => {
                let mut depth = 0;
                loop {
                    match program[pc] {
                        b'[' => depth += 1,
                        b']' => depth -= 1,
                        _ => {}
                    }
                    if depth == 0 {
                        break;
                    }
                    pc += 1;
                }
            }
            b']' if tape[ptr] != 0 => {
                let mut depth = 0;
                loop {
                    match program[pc] {
                        b']' => depth += 1,
                        b'[' => depth -= 1,
                        _ => {}
                    }
                    if depth == 0 {
                        break;
                    }
                    pc -= 1;
                }
            }
            _ => {}
        }
        pc += 1;
    }

    None
}

fn interpret(ast: Vec<AstNode>, input: &[u8]) -> (Vec<u8>, Vec<u8>) {
    let mut interpreter = Interpreter::new(ast);
    let output = TestBuffer::new();
    interpreter.io_write = Box::new(output.clone());
    interpreter.io_read = Box::new(Cursor::new(input.to_vec()));
    let mut steps = 0;
    while interpreter.step().unwrap() {
        steps += 1;
        assert!(steps < 10_000_000, "interpreter doesn't terminate");
    }
    (interpreter.memory[..TAPE].to_vec(), output.get_content())
}

#[cfg(feature = "jit")]
fn jit(ast: Vec<AstNode>, input: &[u8]) -> (Vec<u8>, Vec<u8>) {
    let padding = max_offset(&ast) as usize + TAPE;
    let mut target = JITTarget::new(ast).unwrap();
    let output = TestBuffer::new();
    target.context.borrow_mut().io_write = Box::new(output.clone());
    target.context.borrow_mut().io_read = Box::new(Cursor::new(input.to_vec()));

    let mut memory = vec![0u8; padding + TAPE + padding];
    target.exec(memory[padding..].as_mut_ptr());
    (
        memory[padding..padding + TAPE].to_vec(),
        output.get_content(),
    )
}

/// Check a program against the reference. Returns false if the reference
/// doesn't finish.
fn check(program: &str, input: &[u8], steps: usize) -> bool {
    let Some(expected) = reference(program.as_bytes(), input, steps) else {
        return false;
    };

    // Optimization only preserves what the program observes.
    let observable = AstNode::parse(program, false).unwrap();
    assert_eq!(
        interpret(observable.clone(), input).1,
        expected.1,
        "observable interpreter: {program} {input:?}\n{observable:?}"
    );
    #[cfg(feature = "jit")]
    assert_eq!(
        jit(observable.clone(), input).1,
        expected.1,
        "observable jit: {program} {input:?}\n{observable:?}"
    );

    let ast = AstNode::parse_keeping_tape(program).unwrap();
    assert_eq!(
        interpret(ast.clone(), input),
        expected,
        "interpreter: {program} {input:?}\n{ast:?}"
    );
    #[cfg(feature = "jit")]
    assert_eq!(
        jit(ast.clone(), input),
        expected,
        "jit: {program} {input:?}\n{ast:?}"
    );
    true
}

#[test]
fn optimized_matches_reference() {
    let mut rng = Rng(0x2545_f491_4f6c_dd1d);
    let mut checked = 0;

    while checked < 3000 {
        let mut program = ">".repeat(START);
        generate(&mut rng, 0, &mut program);
        if check(&program, INPUT, 200_000) {
            checked += 1;
        }
    }
}

#[test]
fn multi_byte_edge_cases() {
    let values = [0, 1, 2, 127, 128, 253, 254, 255];

    for (fragment, observe) in MULTI_BYTE {
        // Read the counter and three bytes, then run the fragment.
        let program = format!("{},>,>,>,<<<{fragment}{observe}", ">".repeat(START));
        let mut checked = 0;
        for &counter in &values {
            for &low in &values {
                for &middle in &values {
                    for &high in &[0, 255] {
                        // Some cases take the reference too long.
                        if check(&program, &[counter, low, middle, high], 10_000_000) {
                            checked += 1;
                        }
                    }
                }
            }
        }
        assert!(checked > values.len() * values.len(), "{fragment}");
    }
}

fn random_byte(rng: &mut Rng) -> u8 {
    u8::try_from(rng.below(256)).unwrap()
}

/// One of `cells` cells around the data pointer.
fn random_cell(rng: &mut Rng, cells: usize) -> i32 {
    i32::try_from(rng.below(cells)).unwrap() - i32::try_from(cells / 2).unwrap()
}

fn random_operand(rng: &mut Rng, cells: usize) -> Operand {
    if rng.below(4) == 0 {
        return Operand::constant(random_byte(rng));
    }
    Operand {
        cell: random_cell(rng, cells),
        scale: [1, 1, 1, 255, 2, 3, 4, 7, 254][rng.below(9)],
        bias: [0, 0, 1, 255, random_byte(rng)][rng.below(5)],
    }
}

/// A random straight-line node. Loop bodies don't write to the counter.
fn random_node(rng: &mut Rng, cells: usize, in_loop: bool) -> AstNode {
    let dst = loop {
        let cell = random_cell(rng, cells);
        if !in_loop || cell != 0 {
            break cell;
        }
    };
    let value = [1, 255, random_byte(rng)][rng.below(3)];
    match rng.below(6) {
        0 => AstNode::Add(dst, random_byte(rng)),
        1 => AstNode::Set(dst, random_byte(rng)),
        2 => AstNode::MulAdd {
            src: random_cell(rng, cells),
            dst,
            factor: [1, 255, 2, 3, 4, 254, random_byte(rng)][rng.below(7)],
        },
        3 | 4 => AstNode::CondAdd {
            lhs: random_operand(rng, cells),
            rhs: random_operand(rng, cells),
            dst,
            value,
        },
        _ => AstNode::ProductAdd {
            base: random_operand(rng, cells),
            step: random_operand(rng, cells),
            count: random_operand(rng, cells),
            high: rng.below(2) == 0,
            dst,
            value,
        },
    }
}

/// Random straight-line code on cells read from input, so they aren't known
/// constants, optionally in a loop.
#[cfg(feature = "jit")]
#[test]
fn straight_line_matches_interpreter() {
    let mut rng = Rng(0x9e37_79b9_7f4a_7c15);

    for _ in 0..3000 {
        let cells = [4, 8, 14][rng.below(3)];
        let mut ast = vec![AstNode::Move(i32::try_from(START).unwrap())];
        let first = -i32::try_from(cells / 2).unwrap();
        ast.extend((first..).take(cells).map(AstNode::Read));

        let in_loop = rng.below(2) == 0;
        let mut body: Vec<_> = (0..rng.below(40))
            .map(|_| random_node(&mut rng, cells, in_loop))
            .collect();
        if in_loop {
            body.push(AstNode::Add(0, 255));
            ast.push(AstNode::Loop(body));
            ast.extend((0..rng.below(8)).map(|_| random_node(&mut rng, cells, false)));
        } else {
            ast.extend(body);
        }

        let input: Vec<u8> = (0..cells).map(|_| random_byte(&mut rng)).collect();
        assert_eq!(
            interpret(ast.clone(), &input),
            jit(ast.clone(), &input),
            "{ast:?} {input:?}"
        );
    }
}
