//! Compare optimized execution against a naive reference on random programs.

use std::io::Cursor;

use super::int::Interpreter;
#[cfg(feature = "jit")]
use super::jit::JITTarget;
use super::test_buffer::TestBuffer;
use crate::parser::{AstNode, max_offset};

const TAPE: usize = 64;
/// Programs start by moving to the middle of the tape so they can move left.
const START: usize = 32;
const INPUT: &[u8] = &[7, 0, 255, 1, 3, 128, 2, 254, 9, 0, 1, 5];

/// Multi-byte arithmetic, as generated by compilers targeting brainfuck, and
/// code printing the cells holding the result.
const MULTI_BYTE: &[(&str, &str)] = &[
    // Cells are counter, low byte, high byte, two temporaries.
    // Add the counter with carry: `+` then `high += (low == 0)`
    (
        "[->+>>[-]>[-]+<<<[->>+>[-]<<<]>>[-<<+>>]>[-<<+>>]<<<<]",
        ".>.>.",
    ),
    // Subtract the counter with borrow: `high -= (low == 0)` then `-`
    (
        "[->>>[-]>[-]+<<<[->>+>[-]<<<]>>[-<<+>>]>[-<<->>]<<<-<]",
        ".>.>.",
    ),
    // Same with the counter stepping up
    (
        "[+>+>>[-]>[-]+<<<[->>+>[-]<<<]>>[-<<+>>]>[-<<+>>]<<<<]",
        ".>.>.",
    ),
    // Three byte increment, propagating the carry with nested ifs
    (
        concat!(
            "[->>>>>>[-]<<<<<+>>>[-]>[-]+<<<<[->>>+>[-]<<<<]>>>[-<<<+>>>]",
            ">[-<<<+>>[-]>>[-]+<<<<[->>+>>[-]<<<<]>>[-<<+>>]>>[-<<<+>>>]<]<<<<<]"
        ),
        ".>.>.>.",
    ),
    // Multiply and accumulate: add cell 1 to the two byte number at cells 3
    // and 4 counter times, by copying it to cell 2 (with temporary cell 7)
    // and adding that with carry.
    (
        concat!(
            "[->>[-]>>>>>[-]<<<<<<[->+>>>>>+<<<<<<]>>>>>>[-<<<<<<+>>>>>>]<<<<<",
            "[->+>>[-]>[-]+<<<[->>+>[-]<<<]>>[-<<+>>]>[-<<+>>]<<<<]<<]"
        ),
        ".>.>>.>.",
    ),
];

struct Rng(u64);

impl Rng {
    fn next(&mut self) -> u64 {
        self.0 ^= self.0 << 13;
        self.0 ^= self.0 >> 7;
        self.0 ^= self.0 << 17;
        self.0
    }

    fn below(&mut self, n: usize) -> usize {
        usize::try_from(self.next() % n as u64).unwrap()
    }
}

/// Brainfuck code written cell by cell, keeping track of the data pointer.
#[derive(Default)]
struct Code {
    text: String,
    pointer: i32,
}

impl Code {
    fn goto(&mut self, cell: i32) {
        let step = if cell > self.pointer { ">" } else { "<" };
        self.text
            .push_str(&step.repeat((cell - self.pointer).unsigned_abs() as usize));
        self.pointer = cell;
    }

    fn add(&mut self, cell: i32, amount: i32) {
        self.goto(cell);
        let step = if amount > 0 { "+" } else { "-" };
        self.text
            .push_str(&step.repeat(amount.unsigned_abs() as usize));
    }

    fn clear(&mut self, cell: i32) {
        self.goto(cell);
        self.text.push_str("[-]");
    }

    /// Loop while `cell` is non-zero.
    fn repeat(&mut self, cell: i32, body: impl FnOnce(&mut Self)) {
        self.goto(cell);
        self.text.push('[');
        body(self);
        self.goto(cell);
        self.text.push(']');
    }

    /// Move `src` into `dsts`, adding it to each with the given sign.
    fn move_into(&mut self, src: i32, dsts: &[(i32, i32)]) {
        self.repeat(src, |code| {
            code.add(src, -1);
            for &(dst, sign) in dsts {
                code.add(dst, sign);
            }
        });
    }

    /// Add `src` to the byte `low`, incrementing `high` whenever that wraps.
    /// Clears `src`, using temporaries `t` and `u`.
    fn add_with_carry(&mut self, src: i32, low: i32, high: i32, (t, u): (i32, i32)) {
        self.repeat(src, |code| {
            code.add(src, -1);
            code.add(low, 1);
            code.clear(t);
            code.clear(u);
            code.add(u, 1);
            code.repeat(low, |code| {
                code.add(low, -1);
                code.add(t, 1);
                code.clear(u);
            });
            code.move_into(t, &[(low, 1)]);
            code.move_into(u, &[(high, 1)]);
        });
    }
}

/// A loop dividing the two byte number in cells 1 and 2 by cell 3 through
/// repeated subtraction, counting in cell 4. Cell 0 is the loop flag and
/// cells 5 to 14 are temporaries.
///
/// Like compiled code, it adds the negated divisor and checks for a carry,
/// so the loop also ends when the divisor is zero. With `quirk`, it counts
/// twice when dividing by 200.
fn divide_loop(quirk: bool) -> String {
    let (flag, low, high, divisor, quotient) = (0, 1, 2, 3, 4);
    let (negated_low, negated_high, t, u, carry, done, more, x) = (5, 6, 7, 8, 9, 10, 11, 12);
    let temporaries = (13, 14);

    let mut code = Code::default();
    code.repeat(flag, |code| {
        code.add(flag, -1);

        // negated = 65536 - divisor, where the high byte is 255 unless the
        // divisor is zero
        code.clear(negated_low);
        code.clear(t);
        code.move_into(divisor, &[(negated_low, -1), (t, 1)]);
        code.move_into(t, &[(divisor, 1)]);
        code.clear(u);
        code.move_into(negated_low, &[(t, 1), (u, 1)]);
        code.move_into(u, &[(negated_low, 1)]);
        code.add(u, 1);
        code.repeat(t, |code| {
            code.clear(t);
            code.add(u, -1);
        });
        code.clear(negated_high);
        code.add(negated_high, -1);
        code.move_into(u, &[(negated_high, 1)]);

        // Add it to the dividend, with the carry out in `done`.
        code.clear(carry);
        code.add_with_carry(negated_low, low, carry, temporaries);
        code.clear(done);
        code.add_with_carry(carry, high, done, temporaries);
        code.add_with_carry(negated_high, high, done, temporaries);

        // Count if it didn't drop below zero, otherwise undo that and stop.
        code.clear(more);
        code.add(more, 1);
        code.repeat(done, |code| {
            code.add(done, -1);
            code.add(quotient, 1);
            code.add(flag, 1);
            code.add(more, -1);
            if quirk {
                code.clear(t);
                code.clear(u);
                code.move_into(divisor, &[(t, 1), (u, 1)]);
                code.move_into(u, &[(divisor, 1)]);
                code.add(t, -200);
                code.add(u, 1);
                code.repeat(t, |code| {
                    code.clear(t);
                    code.add(u, -1);
                });
                code.move_into(u, &[(quotient, 1)]);
            }
        });
        code.repeat(more, |code| {
            code.add(more, -1);
            code.clear(t);
            code.clear(x);
            code.move_into(divisor, &[(x, 1), (t, 1)]);
            code.move_into(t, &[(divisor, 1)]);
            code.add_with_carry(x, low, high, temporaries);
            code.clear(flag);
        });
    });
    code.text
}

/// A loop counting down cell 0 and the byte in cell 1, setting cell 2 and
/// stopping early if cell 1 reaches zero first. Cells 3 to 5 are
/// temporaries.
fn count_down_loop() -> String {
    let (counter, value, flag, t, u, zero) = (0, 1, 2, 3, 4, 5);

    let mut code = Code::default();
    code.repeat(counter, |code| {
        code.add(counter, -1);
        code.clear(t);
        code.clear(u);
        code.move_into(value, &[(t, 1), (u, 1)]);
        code.move_into(u, &[(value, 1)]);
        code.clear(zero);
        code.add(zero, 1);
        code.repeat(t, |code| {
            code.clear(t);
            code.add(value, -1);
            code.add(zero, -1);
        });
        code.repeat(zero, |code| {
            code.add(zero, -1);
            code.clear(counter);
            code.add(flag, 1);
        });
    });
    code.text
}

/// Random program biased towards loop idioms the optimizer recognizes.
fn generate(rng: &mut Rng, depth: usize, out: &mut String) {
    for _ in 0..=rng.below(8) {
        match rng.below(15) {
            0..=2 => out.push_str(["+", "-", "+++", "-----"][rng.below(4)]),
            3..=4 => out.push_str([">", "<", ">>", "<<"][rng.below(4)]),
            5 => out.push(','),
            6 => out.push('.'),
            7 => out.push_str(["[-]", "[>]", "[<<]", "[->+<]", "[->>+++<<]"][rng.below(5)]),
            8 => out.push_str(MULTI_BYTE[rng.below(MULTI_BYTE.len())].0),
            _ if depth < 3 => {
                // A loop with a balanced body, sometimes stepping the counter.
                out.push('[');
                if rng.below(2) == 0 {
                    out.push_str(["-", "+", "---", "+++"][rng.below(4)]);
                }
                let mut body = String::new();
                generate(rng, depth + 1, &mut body);
                let balance: i32 = body
                    .chars()
                    .map(|c| match c {
                        '>' => 1,
                        '<' => -1,
                        _ => 0,
                    })
                    .sum();
                out.push_str(&body);
                if rng.below(4) != 0 {
                    let fix = if balance > 0 { "<" } else { ">" };
                    out.push_str(&fix.repeat(balance.unsigned_abs() as usize));
                }
                out.push(']');
            }
            _ => out.push('+'),
        }
    }
}

/// Naive brainfuck. Returns `None` if the program misbehaves or runs too long.
fn reference(program: &[u8], input: &[u8], steps: usize) -> Option<(Vec<u8>, Vec<u8>)> {
    let mut tape = vec![0u8; TAPE];
    let mut output = Vec::new();
    let mut input = input.iter();
    let (mut pc, mut ptr) = (0, 0);

    for _ in 0..steps {
        let Some(&op) = program.get(pc) else {
            return Some((tape, output));
        };
        match op {
            b'+' => tape[ptr] = tape[ptr].wrapping_add(1),
            b'-' => tape[ptr] = tape[ptr].wrapping_sub(1),
            b'>' => ptr = (ptr + 1 < TAPE).then_some(ptr + 1)?,
            b'<' => ptr = ptr.checked_sub(1)?,
            b'.' => output.push(tape[ptr]),
            b',' => tape[ptr] = input.next().copied().unwrap_or(b'\n'),
            b'[' if tape[ptr] == 0 => {
                let mut depth = 0;
                loop {
                    match program[pc] {
                        b'[' => depth += 1,
                        b']' => depth -= 1,
                        _ => {}
                    }
                    if depth == 0 {
                        break;
                    }
                    pc += 1;
                }
            }
            b']' if tape[ptr] != 0 => {
                let mut depth = 0;
                loop {
                    match program[pc] {
                        b']' => depth += 1,
                        b'[' => depth -= 1,
                        _ => {}
                    }
                    if depth == 0 {
                        break;
                    }
                    pc -= 1;
                }
            }
            _ => {}
        }
        pc += 1;
    }

    None
}

fn interpret(ast: Vec<AstNode>, input: &[u8]) -> (Vec<u8>, Vec<u8>) {
    let mut interpreter = Interpreter::new(ast);
    let output = TestBuffer::new();
    interpreter.io_write = Box::new(output.clone());
    interpreter.io_read = Box::new(Cursor::new(input.to_vec()));
    let mut steps = 0;
    while interpreter.step().unwrap() {
        steps += 1;
        assert!(steps < 10_000_000, "interpreter doesn't terminate");
    }
    (interpreter.memory[..TAPE].to_vec(), output.get_content())
}

#[cfg(feature = "jit")]
fn jit(ast: Vec<AstNode>, input: &[u8]) -> (Vec<u8>, Vec<u8>) {
    let padding = max_offset(&ast) as usize + TAPE;
    let mut target = JITTarget::new(ast).unwrap();
    let output = TestBuffer::new();
    target.context.borrow_mut().io_write = Box::new(output.clone());
    target.context.borrow_mut().io_read = Box::new(Cursor::new(input.to_vec()));

    let mut memory = vec![0u8; padding + TAPE + padding];
    target.exec(memory[padding..].as_mut_ptr());
    (
        memory[padding..padding + TAPE].to_vec(),
        output.get_content(),
    )
}

/// Check a program against the reference. Returns false if the reference
/// doesn't finish.
fn check(program: &str, input: &[u8], steps: usize) -> bool {
    let Some(expected) = reference(program.as_bytes(), input, steps) else {
        return false;
    };

    // Optimization only preserves what the program observes.
    let observable = AstNode::parse(program, false).unwrap();
    assert_eq!(
        interpret(observable.clone(), input).1,
        expected.1,
        "observable interpreter: {program} {input:?}\n{observable:?}"
    );
    #[cfg(feature = "jit")]
    assert_eq!(
        jit(observable.clone(), input).1,
        expected.1,
        "observable jit: {program} {input:?}\n{observable:?}"
    );

    let ast = AstNode::parse_keeping_tape(program).unwrap();
    assert_eq!(
        interpret(ast.clone(), input),
        expected,
        "interpreter: {program} {input:?}\n{ast:?}"
    );
    #[cfg(feature = "jit")]
    assert_eq!(
        jit(ast.clone(), input),
        expected,
        "jit: {program} {input:?}\n{ast:?}"
    );
    true
}

#[test]
fn optimized_matches_reference() {
    let mut rng = Rng(0x2545_f491_4f6c_dd1d);
    let mut checked = 0;

    while checked < 3000 {
        let mut program = ">".repeat(START);
        generate(&mut rng, 0, &mut program);
        if check(&program, INPUT, 200_000) {
            checked += 1;
        }
    }
}

#[test]
fn divide_loop_is_accelerated() {
    let program = |quirk| format!(",>,>,>,>,<<<<{}>.>.>.>.", divide_loop(quirk));
    let ast = AstNode::parse(&program(false), false).unwrap();
    // The temporaries aren't used afterwards, so the last iteration isn't
    // needed either.
    assert!(
        matches!(&ast[5], AstNode::Loop(body) if matches!(
            body[..],
            [AstNode::DivMod { .. }, AstNode::Set(0, 0)]
        )),
        "{ast:?}"
    );

    // Otherwise it's still run.
    let program_using_temporary = format!(",>,>,>,>,<<<<{}>>>>>.", divide_loop(false));
    let ast = AstNode::parse(&program_using_temporary, false).unwrap();
    assert!(
        matches!(&ast[5], AstNode::Loop(body) if matches!(
            body[..],
            [AstNode::DivMod { .. }, _, _, ..]
        )),
        "{ast:?}"
    );
    let program_using_temporary = format!("{}{program_using_temporary}", ">".repeat(START));
    for input in [
        [1, 10, 0, 3, 0],
        [1, 0, 0, 0, 0],
        [5, 2, 0, 3, 0],
        [0, 9, 9, 9, 9],
    ] {
        assert!(check(&program_using_temporary, &input, 100_000_000));
    }

    // Random cell values almost never divide by 200, but the proof notices.
    let ast = AstNode::parse(&program(true), false).unwrap();
    assert!(!format!("{ast:?}").contains("DivMod"), "{ast:?}");
    let program = format!("{}{}", ">".repeat(START), program(true));
    assert!(check(&program, &[1, 100, 2, 200, 0], 100_000_000));
}

#[test]
fn divide_loop_edge_cases() {
    let values = [0, 1, 2, 3, 7, 127, 128, 200, 254, 255];
    let program = format!(
        "{},>,>,>,>,<<<<{}>.>.>.>.",
        ">".repeat(START),
        divide_loop(false)
    );
    let observable = AstNode::parse(&program, false).unwrap();
    let ast = AstNode::parse_keeping_tape(&program).unwrap();

    let mut checked = 0;
    for flag in [0, 1, 9] {
        for low in values {
            for high in values {
                for divisor in values {
                    let input = [flag, low, high, divisor, 100];
                    let dividend = u16::from_le_bytes([low, high]);
                    let (remainder, quotient) = if flag == 0 || divisor == 0 {
                        (dividend, 0)
                    } else {
                        let divisor = u16::from(divisor);
                        (dividend % divisor, dividend / divisor)
                    };
                    let [low, high] = remainder.to_le_bytes();
                    let counter = quotient.to_le_bytes()[0].wrapping_add(100);
                    let expected = vec![low, high, divisor, counter];

                    assert_eq!(
                        interpret(observable.clone(), &input).1,
                        expected,
                        "interpreter: {input:?}"
                    );
                    let tape = interpret(ast.clone(), &input).0;
                    #[cfg(feature = "jit")]
                    {
                        assert_eq!(
                            jit(observable.clone(), &input).1,
                            expected,
                            "jit: {input:?}"
                        );
                        assert_eq!(jit(ast.clone(), &input).0, tape, "jit tape: {input:?}");
                    }

                    // The reference is too slow for big numbers.
                    if let Some((expected, _)) = reference(program.as_bytes(), &input, 1_000_000) {
                        assert_eq!(tape, expected, "tape: {input:?}");
                        checked += 1;
                    }
                }
            }
        }
    }
    assert!(checked > 100, "{checked}");
}

#[test]
fn accelerated_loops_in_random_programs() {
    let mut rng = Rng(0x9e37_79b9_7f4a_7c15);
    let loops = [divide_loop(false), count_down_loop()];
    let mut checked = 0;

    for _ in 0..1000 {
        let mut program = ">".repeat(START);
        generate(&mut rng, 1, &mut program);
        program.push_str(&loops[rng.below(loops.len())]);
        generate(&mut rng, 1, &mut program);
        if check(&program, INPUT, 2_000_000) {
            checked += 1;
        }
    }
    assert!(checked > 300, "{checked}");
}

#[test]
fn count_down_loop_edge_cases() {
    let program = format!("{},>,>,<<{}>.>.<<.", ">".repeat(START), count_down_loop());
    let ast = AstNode::parse(&program, false).unwrap();
    assert!(format!("{ast:?}").contains("Skip"), "{ast:?}");

    let values = [0, 1, 2, 3, 100, 127, 128, 129, 254, 255];
    for counter in values {
        for value in values {
            for flag in [0, 7] {
                assert!(check(&program, &[counter, value, flag], 1_000_000));
            }
        }
    }
}

#[test]
fn multi_byte_edge_cases() {
    let values = [0, 1, 2, 127, 128, 253, 254, 255];

    for (fragment, observe) in MULTI_BYTE {
        // Read the counter and three bytes, then run the fragment.
        let program = format!("{},>,>,>,<<<{fragment}{observe}", ">".repeat(START));
        let mut checked = 0;
        for &counter in &values {
            for &low in &values {
                for &middle in &values {
                    for &high in &[0, 255] {
                        // Some cases take the reference too long.
                        if check(&program, &[counter, low, middle, high], 10_000_000) {
                            checked += 1;
                        }
                    }
                }
            }
        }
        assert!(checked > values.len() * values.len(), "{fragment}");
    }
}
