//! Compare optimized execution against a naive reference on random programs.

use std::io::Cursor;

use super::int::Interpreter;
#[cfg(feature = "jit")]
use super::jit::JITTarget;
use super::test_buffer::TestBuffer;
use crate::parser::{AstNode, Operand, WordTerm, lift, max_offset};

const TAPE: usize = 64;
/// Programs start by moving to the middle of the tape so they can move left.
const START: usize = 32;
const INPUT: &[u8] = &[7, 0, 255, 1, 3, 128, 2, 254, 9, 0, 1, 5];

/// Multi-byte arithmetic, as generated by compilers targeting brainfuck, and
/// code printing the cells holding the result.
const MULTI_BYTE: &[(&str, &str)] = &[
    // Cells are counter, low byte, high byte, two temporaries.
    // Add the counter with carry: `+` then `high += (low == 0)`
    (
        "[->+>>[-]>[-]+<<<[->>+>[-]<<<]>>[-<<+>>]>[-<<+>>]<<<<]",
        ".>.>.",
    ),
    // Subtract the counter with borrow: `high -= (low == 0)` then `-`
    (
        "[->>>[-]>[-]+<<<[->>+>[-]<<<]>>[-<<+>>]>[-<<->>]<<<-<]",
        ".>.>.",
    ),
    // Same with the counter stepping up
    (
        "[+>+>>[-]>[-]+<<<[->>+>[-]<<<]>>[-<<+>>]>[-<<+>>]<<<<]",
        ".>.>.",
    ),
    // Three byte increment, propagating the carry with nested ifs
    (
        concat!(
            "[->>>>>>[-]<<<<<+>>>[-]>[-]+<<<<[->>>+>[-]<<<<]>>>[-<<<+>>>]",
            ">[-<<<+>>[-]>>[-]+<<<<[->>+>>[-]<<<<]>>[-<<+>>]>>[-<<<+>>>]<]<<<<<]"
        ),
        ".>.>.>.",
    ),
    // Multiply and accumulate: add cell 1 to the two byte number at cells 3
    // and 4 counter times, by copying it to cell 2 (with temporary cell 7)
    // and adding that with carry.
    (
        concat!(
            "[->>[-]>>>>>[-]<<<<<<[->+>>>>>+<<<<<<]>>>>>>[-<<<<<<+>>>>>>]<<<<<",
            "[->+>>[-]>[-]+<<<[->>+>[-]<<<]>>[-<<+>>]>[-<<+>>]<<<<]<<]"
        ),
        ".>.>>.>.",
    ),
];

struct Rng(u64);

impl Rng {
    fn next(&mut self) -> u64 {
        self.0 ^= self.0 << 13;
        self.0 ^= self.0 >> 7;
        self.0 ^= self.0 << 17;
        self.0
    }

    fn below(&mut self, n: usize) -> usize {
        usize::try_from(self.next() % n as u64).unwrap()
    }
}

/// Brainfuck code written cell by cell, keeping track of the data pointer.
#[derive(Default)]
struct Code {
    text: String,
    pointer: i32,
}

impl Code {
    fn goto(&mut self, cell: i32) {
        let step = if cell > self.pointer { ">" } else { "<" };
        self.text
            .push_str(&step.repeat((cell - self.pointer).unsigned_abs() as usize));
        self.pointer = cell;
    }

    fn add(&mut self, cell: i32, amount: i32) {
        self.goto(cell);
        let step = if amount > 0 { "+" } else { "-" };
        self.text
            .push_str(&step.repeat(amount.unsigned_abs() as usize));
    }

    fn clear(&mut self, cell: i32) {
        self.goto(cell);
        self.text.push_str("[-]");
    }

    /// Loop while `cell` is non-zero.
    fn repeat(&mut self, cell: i32, body: impl FnOnce(&mut Self)) {
        self.goto(cell);
        self.text.push('[');
        body(self);
        self.goto(cell);
        self.text.push(']');
    }

    /// Move `src` into `dsts`, adding it to each with the given sign.
    fn move_into(&mut self, src: i32, dsts: &[(i32, i32)]) {
        self.repeat(src, |code| {
            code.add(src, -1);
            for &(dst, sign) in dsts {
                code.add(dst, sign);
            }
        });
    }

    /// Add `src` to the byte `low`, incrementing `high` whenever that wraps.
    /// Clears `src`, using temporaries `t` and `u`.
    fn add_with_carry(&mut self, src: i32, low: i32, high: i32, (t, u): (i32, i32)) {
        self.repeat(src, |code| {
            code.add(src, -1);
            code.add(low, 1);
            code.clear(t);
            code.clear(u);
            code.add(u, 1);
            code.repeat(low, |code| {
                code.add(low, -1);
                code.add(t, 1);
                code.clear(u);
            });
            code.move_into(t, &[(low, 1)]);
            code.move_into(u, &[(high, 1)]);
        });
    }
}

/// A loop dividing the two byte number in cells 1 and 2 by cell 3 through
/// repeated subtraction, counting in cell 4. Cell 0 is the loop flag and
/// cells 5 to 14 are temporaries.
///
/// Like compiled code, it adds the negated divisor and checks for a carry,
/// so the loop also ends when the divisor is zero. With `quirk`, it counts
/// twice when dividing by 200.
fn divide_loop(quirk: bool) -> String {
    let (flag, low, high, divisor, quotient) = (0, 1, 2, 3, 4);
    let (negated_low, negated_high, t, u, carry, done, more, x) = (5, 6, 7, 8, 9, 10, 11, 12);
    let temporaries = (13, 14);

    let mut code = Code::default();
    code.repeat(flag, |code| {
        code.add(flag, -1);

        // negated = 65536 - divisor, where the high byte is 255 unless the
        // divisor is zero
        code.clear(negated_low);
        code.clear(t);
        code.move_into(divisor, &[(negated_low, -1), (t, 1)]);
        code.move_into(t, &[(divisor, 1)]);
        code.clear(u);
        code.move_into(negated_low, &[(t, 1), (u, 1)]);
        code.move_into(u, &[(negated_low, 1)]);
        code.add(u, 1);
        code.repeat(t, |code| {
            code.clear(t);
            code.add(u, -1);
        });
        code.clear(negated_high);
        code.add(negated_high, -1);
        code.move_into(u, &[(negated_high, 1)]);

        // Add it to the dividend, with the carry out in `done`.
        code.clear(carry);
        code.add_with_carry(negated_low, low, carry, temporaries);
        code.clear(done);
        code.add_with_carry(carry, high, done, temporaries);
        code.add_with_carry(negated_high, high, done, temporaries);

        // Count if it didn't drop below zero, otherwise undo that and stop.
        code.clear(more);
        code.add(more, 1);
        code.repeat(done, |code| {
            code.add(done, -1);
            code.add(quotient, 1);
            code.add(flag, 1);
            code.add(more, -1);
            if quirk {
                code.clear(t);
                code.clear(u);
                code.move_into(divisor, &[(t, 1), (u, 1)]);
                code.move_into(u, &[(divisor, 1)]);
                code.add(t, -200);
                code.add(u, 1);
                code.repeat(t, |code| {
                    code.clear(t);
                    code.add(u, -1);
                });
                code.move_into(u, &[(quotient, 1)]);
            }
        });
        code.repeat(more, |code| {
            code.add(more, -1);
            code.clear(t);
            code.clear(x);
            code.move_into(divisor, &[(x, 1), (t, 1)]);
            code.move_into(t, &[(divisor, 1)]);
            code.add_with_carry(x, low, high, temporaries);
            code.clear(flag);
        });
    });
    code.text
}

/// A loop counting down cell 0 and the byte in cell 1, setting cell 2 and
/// stopping early if cell 1 reaches zero first. Cells 3 to 5 are
/// temporaries.
fn count_down_loop() -> String {
    let (counter, value, flag, t, u, zero) = (0, 1, 2, 3, 4, 5);

    let mut code = Code::default();
    code.repeat(counter, |code| {
        code.add(counter, -1);
        code.clear(t);
        code.clear(u);
        code.move_into(value, &[(t, 1), (u, 1)]);
        code.move_into(u, &[(value, 1)]);
        code.clear(zero);
        code.add(zero, 1);
        code.repeat(t, |code| {
            code.clear(t);
            code.add(value, -1);
            code.add(zero, -1);
        });
        code.repeat(zero, |code| {
            code.add(zero, -1);
            code.clear(counter);
            code.add(flag, 1);
        });
    });
    code.text
}

/// Random program biased towards loop idioms the optimizer recognizes.
fn generate(rng: &mut Rng, depth: usize, out: &mut String) {
    for _ in 0..=rng.below(8) {
        match rng.below(15) {
            0..=2 => out.push_str(["+", "-", "+++", "-----"][rng.below(4)]),
            3..=4 => out.push_str([">", "<", ">>", "<<"][rng.below(4)]),
            5 => out.push(','),
            6 => out.push('.'),
            7 => out.push_str(["[-]", "[>]", "[<<]", "[->+<]", "[->>+++<<]"][rng.below(5)]),
            8 => out.push_str(MULTI_BYTE[rng.below(MULTI_BYTE.len())].0),
            _ if depth < 3 => {
                // A loop with a balanced body, sometimes stepping the counter.
                out.push('[');
                if rng.below(2) == 0 {
                    out.push_str(["-", "+", "---", "+++"][rng.below(4)]);
                }
                let mut body = String::new();
                generate(rng, depth + 1, &mut body);
                let balance: i32 = body
                    .chars()
                    .map(|c| match c {
                        '>' => 1,
                        '<' => -1,
                        _ => 0,
                    })
                    .sum();
                out.push_str(&body);
                if rng.below(4) != 0 {
                    let fix = if balance > 0 { "<" } else { ">" };
                    out.push_str(&fix.repeat(balance.unsigned_abs() as usize));
                }
                out.push(']');
            }
            _ => out.push('+'),
        }
    }
}

/// Naive brainfuck. Returns `None` if the program misbehaves or runs too long.
fn reference(program: &[u8], input: &[u8], steps: usize) -> Option<(Vec<u8>, Vec<u8>)> {
    let mut tape = vec![0u8; TAPE];
    let mut output = Vec::new();
    let mut input = input.iter();
    let (mut pc, mut ptr) = (0, 0);

    for _ in 0..steps {
        let Some(&op) = program.get(pc) else {
            return Some((tape, output));
        };
        match op {
            b'+' => tape[ptr] = tape[ptr].wrapping_add(1),
            b'-' => tape[ptr] = tape[ptr].wrapping_sub(1),
            b'>' => ptr = (ptr + 1 < TAPE).then_some(ptr + 1)?,
            b'<' => ptr = ptr.checked_sub(1)?,
            b'.' => output.push(tape[ptr]),
            b',' => tape[ptr] = input.next().copied().unwrap_or(b'\n'),
            b'[' if tape[ptr] == 0 => {
                let mut depth = 0;
                loop {
                    match program[pc] {
                        b'[' => depth += 1,
                        b']' => depth -= 1,
                        _ => {}
                    }
                    if depth == 0 {
                        break;
                    }
                    pc += 1;
                }
            }
            b']' if tape[ptr] != 0 => {
                let mut depth = 0;
                loop {
                    match program[pc] {
                        b']' => depth += 1,
                        b'[' => depth -= 1,
                        _ => {}
                    }
                    if depth == 0 {
                        break;
                    }
                    pc -= 1;
                }
            }
            _ => {}
        }
        pc += 1;
    }

    None
}

fn interpret(ast: Vec<AstNode>, input: &[u8]) -> (Vec<u8>, Vec<u8>) {
    let mut interpreter = Interpreter::new(ast);
    let output = TestBuffer::new();
    interpreter.io_write = Box::new(output.clone());
    interpreter.io_read = Box::new(Cursor::new(input.to_vec()));
    let mut steps = 0;
    while interpreter.step().unwrap() {
        steps += 1;
        assert!(steps < 10_000_000, "interpreter doesn't terminate");
    }
    (interpreter.memory[..TAPE].to_vec(), output.get_content())
}

#[cfg(feature = "jit")]
fn jit(ast: Vec<AstNode>, input: &[u8]) -> (Vec<u8>, Vec<u8>) {
    let padding = max_offset(&ast) as usize + TAPE;
    let mut target = JITTarget::new(ast).unwrap();
    let output = TestBuffer::new();
    target.context.borrow_mut().io_write = Box::new(output.clone());
    target.context.borrow_mut().io_read = Box::new(Cursor::new(input.to_vec()));

    let mut memory = vec![0u8; padding + TAPE + padding];
    target.exec(memory[padding..].as_mut_ptr());
    (
        memory[padding..padding + TAPE].to_vec(),
        output.get_content(),
    )
}

/// Check a program against the reference. Returns false if the reference
/// doesn't finish.
fn check(program: &str, input: &[u8], steps: usize) -> bool {
    let Some(expected) = reference(program.as_bytes(), input, steps) else {
        return false;
    };

    // Optimization only preserves what the program observes.
    let observable = AstNode::parse(program, false).unwrap();
    assert_eq!(
        interpret(observable.clone(), input).1,
        expected.1,
        "observable interpreter: {program} {input:?}\n{observable:?}"
    );
    #[cfg(feature = "jit")]
    assert_eq!(
        jit(observable.clone(), input).1,
        expected.1,
        "observable jit: {program} {input:?}\n{observable:?}"
    );

    let ast = AstNode::parse_keeping_tape(program).unwrap();
    assert_eq!(
        interpret(ast.clone(), input),
        expected,
        "interpreter: {program} {input:?}\n{ast:?}"
    );
    #[cfg(feature = "jit")]
    assert_eq!(
        jit(ast.clone(), input),
        expected,
        "jit: {program} {input:?}\n{ast:?}"
    );
    true
}

#[test]
fn optimized_matches_reference() {
    let mut rng = Rng(0x2545_f491_4f6c_dd1d);
    let mut checked = 0;

    while checked < 3000 {
        let mut program = ">".repeat(START);
        generate(&mut rng, 0, &mut program);
        if check(&program, INPUT, 200_000) {
            checked += 1;
        }
    }
}

#[test]
fn divide_loop_is_accelerated() {
    let program = |quirk| format!(",>,>,>,>,<<<<{}>.>.>.>.", divide_loop(quirk));
    let ast = AstNode::parse(&program(false), false).unwrap();
    // The temporaries aren't used afterwards, so the last iteration isn't
    // needed either.
    assert!(
        matches!(&ast[5], AstNode::Loop(body) if matches!(
            body[..],
            [AstNode::DivMod { .. }, AstNode::Set(0, 0)]
        )),
        "{ast:?}"
    );

    // Otherwise it's still run.
    let program_using_temporary = format!(",>,>,>,>,<<<<{}>>>>>.", divide_loop(false));
    let ast = AstNode::parse(&program_using_temporary, false).unwrap();
    assert!(
        matches!(&ast[5], AstNode::Loop(body) if matches!(
            body[..],
            [AstNode::DivMod { .. }, _, _, ..]
        )),
        "{ast:?}"
    );
    let program_using_temporary = format!("{}{program_using_temporary}", ">".repeat(START));
    for input in [
        [1, 10, 0, 3, 0],
        [1, 0, 0, 0, 0],
        [5, 2, 0, 3, 0],
        [0, 9, 9, 9, 9],
    ] {
        assert!(check(&program_using_temporary, &input, 100_000_000));
    }

    // Random cell values almost never divide by 200, but the proof notices.
    let ast = AstNode::parse(&program(true), false).unwrap();
    assert!(!format!("{ast:?}").contains("DivMod"), "{ast:?}");
    let program = format!("{}{}", ">".repeat(START), program(true));
    assert!(check(&program, &[1, 100, 2, 200, 0], 100_000_000));
}

#[test]
fn divide_loop_edge_cases() {
    let values = [0, 1, 2, 3, 7, 127, 128, 200, 254, 255];
    let program = format!(
        "{},>,>,>,>,<<<<{}>.>.>.>.",
        ">".repeat(START),
        divide_loop(false)
    );
    let observable = AstNode::parse(&program, false).unwrap();
    let ast = AstNode::parse_keeping_tape(&program).unwrap();

    let mut checked = 0;
    for flag in [0, 1, 9] {
        for low in values {
            for high in values {
                for divisor in values {
                    let input = [flag, low, high, divisor, 100];
                    let dividend = u16::from_le_bytes([low, high]);
                    let (remainder, quotient) = if flag == 0 || divisor == 0 {
                        (dividend, 0)
                    } else {
                        let divisor = u16::from(divisor);
                        (dividend % divisor, dividend / divisor)
                    };
                    let [low, high] = remainder.to_le_bytes();
                    let counter = quotient.to_le_bytes()[0].wrapping_add(100);
                    let expected = vec![low, high, divisor, counter];

                    assert_eq!(
                        interpret(observable.clone(), &input).1,
                        expected,
                        "interpreter: {input:?}"
                    );
                    let tape = interpret(ast.clone(), &input).0;
                    #[cfg(feature = "jit")]
                    {
                        assert_eq!(
                            jit(observable.clone(), &input).1,
                            expected,
                            "jit: {input:?}"
                        );
                        assert_eq!(jit(ast.clone(), &input).0, tape, "jit tape: {input:?}");
                    }

                    // The reference is too slow for big numbers.
                    if let Some((expected, _)) = reference(program.as_bytes(), &input, 1_000_000) {
                        assert_eq!(tape, expected, "tape: {input:?}");
                        checked += 1;
                    }
                }
            }
        }
    }
    assert!(checked > 100, "{checked}");
}

#[test]
fn accelerated_loops_in_random_programs() {
    let mut rng = Rng(0x9e37_79b9_7f4a_7c15);
    let loops = [divide_loop(false), count_down_loop()];
    let mut checked = 0;

    for _ in 0..1000 {
        let mut program = ">".repeat(START);
        generate(&mut rng, 1, &mut program);
        program.push_str(&loops[rng.below(loops.len())]);
        generate(&mut rng, 1, &mut program);
        if check(&program, INPUT, 2_000_000) {
            checked += 1;
        }
    }
    assert!(checked > 300, "{checked}");
}

#[test]
fn count_down_loop_edge_cases() {
    let program = format!("{},>,>,<<{}>.>.<<.", ">".repeat(START), count_down_loop());
    let ast = AstNode::parse(&program, false).unwrap();
    assert!(format!("{ast:?}").contains("Skip"), "{ast:?}");

    let values = [0, 1, 2, 3, 100, 127, 128, 129, 254, 255];
    for counter in values {
        for value in values {
            for flag in [0, 7] {
                assert!(check(&program, &[counter, value, flag], 1_000_000));
            }
        }
    }
}

#[test]
fn multi_byte_edge_cases() {
    let values = [0, 1, 2, 127, 128, 253, 254, 255];

    for (fragment, observe) in MULTI_BYTE {
        // Read the counter and three bytes, then run the fragment.
        let program = format!("{},>,>,>,<<<{fragment}{observe}", ">".repeat(START));
        let mut checked = 0;
        for &counter in &values {
            for &low in &values {
                for &middle in &values {
                    for &high in &[0, 255] {
                        // Some cases take the reference too long.
                        if check(&program, &[counter, low, middle, high], 10_000_000) {
                            checked += 1;
                        }
                    }
                }
            }
        }
        assert!(checked > values.len() * values.len(), "{fragment}");
    }
}

fn random_byte(rng: &mut Rng) -> u8 {
    u8::try_from(rng.below(256)).unwrap()
}

/// One of `cells` cells around the data pointer.
fn random_cell(rng: &mut Rng, cells: usize) -> i32 {
    i32::try_from(rng.below(cells)).unwrap() - i32::try_from(cells / 2).unwrap()
}

fn random_operand(rng: &mut Rng, cells: usize) -> Operand {
    if rng.below(4) == 0 {
        return Operand::constant([0, 1, 254, 255, random_byte(rng)][rng.below(5)]);
    }
    Operand {
        cell: random_cell(rng, cells),
        scale: [1, 1, 1, 255, 2, 3, 4, 7, 254][rng.below(9)],
        bias: [0, 0, 1, 255, random_byte(rng)][rng.below(5)],
    }
}

/// A random cell, other than the loop counter if in a loop.
fn random_dst(rng: &mut Rng, cells: usize, in_loop: bool) -> i32 {
    loop {
        let cell = random_cell(rng, cells);
        if !in_loop || cell != 0 {
            return cell;
        }
    }
}

/// A random straight-line node, a byte addition with carry, or a loop which
/// only sets cells and runs at most once, between pointer movements. Loop
/// bodies don't write to the counter.
fn random_nodes(rng: &mut Rng, cells: usize, in_loop: bool) -> Vec<AstNode> {
    let dst = random_dst(rng, cells, in_loop);
    let value = [1, 255, random_byte(rng)][rng.below(3)];
    if rng.below(5) == 0 {
        // The counter and cells set are relative to the moved pointer.
        let counter = random_dst(rng, cells, in_loop);
        let mut body: Vec<_> = (0..rng.below(4))
            .map(|_| AstNode::Set(random_dst(rng, cells, in_loop) - counter, random_byte(rng)))
            .filter(|node| !matches!(node, AstNode::Set(0, _)))
            .collect();
        body.insert(rng.below(body.len() + 1), AstNode::Set(0, 0));
        return vec![
            AstNode::Move(counter),
            AstNode::Loop(body),
            AstNode::Move(-counter),
        ];
    }
    if rng.below(8) == 0 {
        return vec![random_word(rng, cells, in_loop)];
    }
    if rng.below(7) == 0 {
        let sum = random_dst(rng, cells, in_loop);
        let addend = random_cell(rng, cells);
        return vec![
            AstNode::CondAdd {
                lhs: Operand {
                    cell: sum,
                    scale: 255,
                    bias: 255,
                },
                rhs: Operand::cell(addend),
                dst,
                value,
            },
            AstNode::MulAdd {
                src: addend,
                dst: sum,
                factor: 1,
            },
        ];
    }
    vec![match rng.below(6) {
        0 => AstNode::Add(dst, random_byte(rng)),
        1 => AstNode::Set(dst, random_byte(rng)),
        2 => AstNode::MulAdd {
            src: random_cell(rng, cells),
            dst,
            factor: [1, 255, 2, 3, 4, 254, random_byte(rng)][rng.below(7)],
        },
        3 | 4 => AstNode::CondAdd {
            lhs: random_operand(rng, cells),
            rhs: random_operand(rng, cells),
            dst,
            value,
        },
        _ => AstNode::ProductAdd {
            base: random_operand(rng, cells),
            step: random_operand(rng, cells),
            count: random_operand(rng, cells),
            high: rng.below(2) == 0,
            dst,
            value,
        },
    }]
}

/// A random little-endian number of up to `max_len` cells around the data
/// pointer.
fn random_number(rng: &mut Rng, cells: usize, max_len: u8) -> (i32, u8) {
    let len = u8::try_from(rng.below(usize::from(max_len).min(cells)) + 1).unwrap();
    let first = -i32::try_from(cells / 2).unwrap();
    let last = first + i32::try_from(cells).unwrap() - i32::from(len);
    let start =
        first + i32::try_from(rng.below(usize::try_from(last - first + 1).unwrap())).unwrap();
    (start, len)
}

/// A random `Word` node, which doesn't write to the loop counter if in a
/// loop.
fn random_word(rng: &mut Rng, cells: usize, in_loop: bool) -> AstNode {
    let (dst, len) = loop {
        let (dst, len) = random_number(rng, cells, 8);
        if !in_loop || !(dst..dst + i32::from(len)).contains(&0) {
            break (dst, len);
        }
    };
    let terms = (0..rng.below(3))
        .map(|_| {
            let (cell, len) = random_number(rng, cells, 8);
            let times = (rng.below(3) == 0 && len < 8).then(|| random_number(rng, cells, 8 - len));
            let width = len + times.map_or(0, |(_, len)| len);
            WordTerm {
                cell,
                len,
                times,
                shift: u8::try_from(rng.below(usize::from(width))).unwrap(),
                negate: rng.below(2) == 0,
            }
        })
        .collect();
    AstNode::Word {
        dst,
        len,
        terms,
        constant: rng.next(),
    }
}

/// Random straight-line code on cells read from input, so they aren't known
/// constants, optionally in a loop.
#[cfg(feature = "jit")]
#[test]
fn straight_line_matches_interpreter() {
    let mut rng = Rng(0x9e37_79b9_7f4a_7c15);

    for _ in 0..3000 {
        let cells = [4, 8, 14, 24][rng.below(4)];
        let mut ast = vec![AstNode::Move(i32::try_from(START).unwrap())];
        let first = -i32::try_from(cells / 2).unwrap();
        ast.extend((first..).take(cells).map(AstNode::Read));

        let in_loop = rng.below(2) == 0;
        let mut body: Vec<_> = (0..rng.below(40))
            .flat_map(|_| random_nodes(&mut rng, cells, in_loop))
            .collect();
        if in_loop {
            body.push(AstNode::Add(0, 255));
            ast.push(AstNode::Loop(body));
            ast.extend((0..rng.below(8)).flat_map(|_| random_nodes(&mut rng, cells, false)));
        } else {
            ast.extend(body);
        }

        let input: Vec<u8> = (0..cells).map(|_| random_byte(&mut rng)).collect();
        assert_eq!(
            interpret(ast.clone(), &input),
            jit(ast.clone(), &input),
            "{ast:?} {input:?}"
        );
    }
}

/// Straight-line code doing arithmetic on 32-bit numbers the way compilers
/// targeting brainfuck do, a byte at a time.
mod compiled {
    use crate::parser::{AstNode, Operand};

    /// `~cell`, as an operand
    const fn complement(cell: i32) -> Operand {
        Operand {
            cell,
            scale: u8::MAX,
            bias: u8::MAX,
        }
    }

    pub fn copy(nodes: &mut Vec<AstNode>, src: i32, dst: i32) {
        for i in 0..4 {
            nodes.push(AstNode::Set(dst + i, 0));
            nodes.push(AstNode::MulAdd {
                src: src + i,
                dst: dst + i,
                factor: 1,
            });
        }
    }

    pub fn not(nodes: &mut Vec<AstNode>, cell: i32) {
        for i in 0..4 {
            nodes.push(AstNode::MulAdd {
                src: cell + i,
                dst: cell + i,
                factor: 254,
            });
            nodes.push(AstNode::Add(cell + i, u8::MAX));
        }
    }

    /// Add the byte in `addend` to the number from byte `from` of the one in
    /// `number`, carrying with temporaries `carries`. Clears `addend`.
    pub fn add_byte(
        nodes: &mut Vec<AstNode>,
        number: i32,
        from: i32,
        mut addend: i32,
        [mut carry, mut next]: [i32; 2],
    ) {
        for i in from..4 {
            nodes.push(AstNode::Set(next, 0));
            nodes.push(AstNode::CondAdd {
                lhs: complement(number + i),
                rhs: Operand::cell(addend),
                dst: next,
                value: 1,
            });
            nodes.push(AstNode::MulAdd {
                src: addend,
                dst: number + i,
                factor: 1,
            });
            nodes.push(AstNode::Set(addend, 0));
            (addend, carry, next) = (next, addend, carry);
        }
        let _ = carry;
    }

    /// number += addend, both 32-bit.
    pub fn add(nodes: &mut Vec<AstNode>, number: i32, addend: i32, temporaries: [i32; 3]) {
        let [byte, carries @ ..] = temporaries;
        for i in 0..4 {
            nodes.push(AstNode::Set(byte, 0));
            nodes.push(AstNode::MulAdd {
                src: addend + i,
                dst: byte,
                factor: 1,
            });
            add_byte(nodes, number, i, byte, carries);
        }
    }

    /// cell = -cell
    pub fn negate(nodes: &mut Vec<AstNode>, cell: i32, temporaries: [i32; 3]) {
        not(nodes, cell);
        let [one, carries @ ..] = temporaries;
        nodes.push(AstNode::Set(one, 1));
        add_byte(nodes, cell, 0, one, carries);
    }

    /// dst = x * y, schoolbook, keeping only the low 32 bits.
    pub fn multiply(nodes: &mut Vec<AstNode>, x: i32, y: i32, dst: i32, temporaries: [i32; 3]) {
        let [high, carries @ ..] = temporaries;
        for i in 0..4 {
            nodes.push(AstNode::Set(dst + i, 0));
        }
        for i in 0..4 {
            for j in 0..4 - i {
                let k = dst + i + j;
                nodes.push(AstNode::Set(high, 0));
                nodes.push(AstNode::ProductAdd {
                    base: Operand::cell(k),
                    step: Operand::cell(x + i),
                    count: Operand::cell(y + j),
                    high: true,
                    dst: high,
                    value: 1,
                });
                nodes.push(AstNode::ProductAdd {
                    base: Operand::constant(0),
                    step: Operand::cell(x + i),
                    count: Operand::cell(y + j),
                    high: false,
                    dst: k,
                    value: 1,
                });
                if i + j < 3 {
                    add_byte(nodes, dst, i + j + 1, high, carries);
                }
            }
        }
    }
}

/// Compiled 32-bit arithmetic is lifted to `Word` nodes which leave the same
/// observable results.
#[test]
fn compiled_arithmetic_is_lifted() {
    use compiled::{add, copy, multiply, negate};

    // x, y and the result are 32-bit numbers, then temporaries.
    let (x, y, result, copied, sum) = (0, 4, 8, 12, 16);
    let temporaries = [20, 21, 22];
    let mut nodes = vec![AstNode::Move(i32::try_from(START).unwrap())];
    nodes.extend((0..8).map(AstNode::Read));
    let mut run = Vec::new();
    copy(&mut run, x, copied);
    negate(&mut run, copied, temporaries);
    copy(&mut run, x, sum);
    add(&mut run, sum, y, temporaries);
    multiply(&mut run, x, y, result, temporaries);
    nodes.extend(run);
    nodes.extend(
        (copied..sum + 4)
            .chain(result..result + 4)
            .map(AstNode::Print),
    );

    let lifted = lift(nodes.clone(), false);
    let words = |product: bool| {
        lifted.iter().any(|node| {
            matches!(node, AstNode::Word { terms, .. }
                if terms.iter().any(|term| term.times.is_some() == product))
        })
    };
    assert!(words(false) && words(true), "{lifted:?}");
    assert!(lifted.len() < nodes.len() / 4, "{lifted:?}");

    let mut rng = Rng(0x2545_f491_4f6c_dd1d);
    let edges = [0, 1, 2, 127, 128, 254, 255];
    for _ in 0..2000 {
        let input: Vec<u8> = (0..8)
            .map(|_| {
                if rng.below(2) == 0 {
                    edges[rng.below(edges.len())]
                } else {
                    random_byte(&mut rng)
                }
            })
            .collect();
        let expected = interpret(nodes.clone(), &input).1;
        let [x0, x1, x2, x3, y0, y1, y2, y3] = input[..] else {
            unreachable!()
        };
        let (x, y) = (
            u32::from_le_bytes([x0, x1, x2, x3]),
            u32::from_le_bytes([y0, y1, y2, y3]),
        );
        let reference: Vec<u8> = [x.wrapping_neg(), x.wrapping_add(y), x.wrapping_mul(y)]
            .iter()
            .flat_map(|number| number.to_le_bytes())
            .collect();
        assert_eq!(expected, reference, "{input:?}");
        assert_eq!(interpret(lifted.clone(), &input).1, expected, "{input:?}");
        #[cfg(feature = "jit")]
        assert_eq!(jit(lifted.clone(), &input).1, expected, "{input:?}");
    }
}

/// Code which almost always computes a sum is only lifted if it always does,
/// whatever the samples guessing it show.
#[test]
fn lifting_is_proven() {
    let (x, sum, flag) = (0, 4, 8);
    let temporaries = [9, 10, 11];
    let mut nodes = vec![AstNode::Move(i32::try_from(START).unwrap())];
    nodes.extend((x..x + 4).map(AstNode::Read));
    let mut run = Vec::new();
    // sum = x + 1, plus 1 more in the low byte if it's 200
    compiled::copy(&mut run, x, sum);
    run.push(AstNode::Set(temporaries[0], 1));
    compiled::add_byte(&mut run, sum, 0, temporaries[0], [10, 11]);
    run.extend([
        AstNode::Set(flag, 0),
        AstNode::CondAdd {
            lhs: Operand::constant(199),
            rhs: Operand::cell(x),
            dst: flag,
            value: 1,
        },
        AstNode::CondAdd {
            lhs: Operand::constant(200),
            rhs: Operand::cell(x),
            dst: flag,
            value: u8::MAX,
        },
        AstNode::MulAdd {
            src: flag,
            dst: sum,
            factor: 1,
        },
    ]);
    nodes.extend(run);
    nodes.extend((sum..sum + 4).map(AstNode::Print));

    let lifted = lift(nodes.clone(), false);
    for low in [0, 199, 200, 201, 255] {
        let input = [low, 0, 255, 7];
        let expected = interpret(nodes.clone(), &input).1;
        assert_eq!(interpret(lifted.clone(), &input).1, expected, "{lifted:?}");
    }
}
