[package]
name = "fucker"
version = "0.5.3"
authors = ["teaearlgraycold <teaearlgraycold@protonmail.com>"]
homepage = "https://github.com/danthedaniel/BrainFuck"
repository = "https://github.com/danthedaniel/BrainFuck"
description = "BrainFuck interpreter and optimizing JIT compiler "
readme = "README.md"
license = "MIT"

[dependencies]
libc = "0.2"
docopt = "1.1.0"
serde = "1.0"
serde_derive = "1.0"

[[bin]]
name = "fucker"
doc = false
test = true

[profile.release]
debug = true
