[package]
name = "fucker"
version = "0.3.0"
authors = ["teaearlgraycold <teaearlgraycold@protonmail.com>"]

[dependencies]
libc = "0.2"
docopt = "1.1.0"
serde = "1.0"
serde_derive = "1.0"

[[bin]]
name = "fucker"
doc = false
test = false
